### GET Vehicules

GET http://localhost:3000/vehicules HTTP/1.1


### POST Vehicule
POST http://localhost:3000/vehicule HTTP/1.1
Content-Type: application/json

{
  "marque": "Peugeot",
  "modele": "208",
  "couleur": "rouge",
  "immatriculation": "AA-123-BB",
  "annee": 2018,
  "prix": 2000000
}

### UPDATE Vehicule
PUT http://localhost:3000/vehicule/6b1b0ed5-937d-4eed-a5a9-af7650d89f78 HTTP/1.1
Content-Type: application/json

{
  "marque": "Peugeot",
  "modele": "210",
  "couleur": "noire",
  "immatriculation": "AA-123-BB",
  "annee": 2020,
  "prix": 2500000
} 

### GET Vehicule by id
GET http://localhost:3000/vehicule/6f4d9a42-39df-4e02-aa0e-8882911e55e2 HTTP/1.1

### GET Vehicule by Inmatriculation
GET http://localhost:3000/vehicule/search/ABC1 HTTP/1.1


### DELETE Vehicule
DELETE http://localhost:3000/vehicule/48f2d887-db5e-464f-bdea-303cf1fa622b HTTP/1.1